version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - backend
  ui:
    build: ./ui
    image: ${USERNAME}/ui:1.0
    ports:
      -  9292:9292/tcp
    networks:
      - frontend
  post:
    build: ./post-py
    image: ${USERNAME}/post:1.0
    networks:
      - frontend
      - backend
  comment:
    build: ./comment
    image: ${USERNAME}/comment:1.0
    networks:
      - frontend
      - backend

volumes:
  post_db:

networks:
  frontend:
  backend:
